### ISSUE TITLE
[Suggestion] Set default speeds for in combat and out of combat

### ISSUE THREAD

**Issue by Shaniquaniminiquani** [willis81808/TheBazaarCombatAccelerator#1]
Set a default speed multiplier for in combat and everywhere else. I tend to find myself going to 5x on fights but moving back down to 2x for everything else. Just a Qol suggestion

**Comment by willis81808** [comment]
The speed-up is only active in combat. 2x, 5x, what have you, don't have any impact on play outside of combat. It is not necessary to change the multiplier for non-combat play.
